#!/bin/bash

# This file is part of the SPFE Open Toolkit. See the accompanying license.txt file for applicable licenses.
# (c) Copyright Analecta Communications Inc. 2012 All Rights Reserved.

#SPFE
export SPFEOT_HOME=/Users/John/workspace/spfe-open-toolkit/spfe-ot
export SPFE_BUILD_DIR=/Users/John/spfe-user-build

date |tee build.log

if [ -e ${SPFE_BUILD_DIR} ]; then
    echo "NOT Removing ${SPFE_BUILD_DIR}" |tee -a build.log
    # rm -rf ${SPFE_BUILD_DIR}
fi

exec $SPFEOT_HOME/spfe.sh spfe-user-config.xml "$@" 2>&1 |tee -a build.log


